### ISSUE TITLE
【意見】ino-vation に＋１

### ISSUE THREAD

**Issue by mapconcierge** [handygeospatial/tadataka-san-no-innovation#3]
現時点では ino-vation に＋１です。

理由：
- 英単語 innovation を綴り間違った問題はクリアしなければならない
- なるべく文字数は少なくしたい
- ハイフンをいれることで inōvation のニュアンスが入る
- ハイフンをいれることで イノー のニュアンスが入る
- ino-vation ドメインは空いている

**Comment by handygeospatial** [comment]
これで落ち着きますね。これで行きましょう。クローズします。
